common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: guillotine
  password:
  host: localhost

development:
  <<: *common
  database: guillotine_development

test:
  <<: *common
  database: guillotine_test

production:
  <<: *common
  database: guillotine_production
